### PR TITLE
Added expressions page

### PR DESCRIPTION
**Pull request by btegenbosch**
Added expressions page.
No HTML exported

### CODE REVIEW

**Comment by vincentfree** [comment]
No problem I'll export later today or tomorrow

**Comment by vincentfree** [comment]
See if you have my latest version, I already added flow control with expressions vs statements. You can merge your stuff in there since mine was just an example no text

**Comment by btegenbosch** [comment]
I was so free to take the ternary operator quote and remove the rest. If I removed something you want to keep I'll revert or we can discuss tomorrow.

Mainly my goal was to keep simple examples as some are a bit hard to read in a glance.

**Comment by vincentfree** [comment]
Most of the later stuff was straight from the kotlin site and there to rifine anyway so fine with me ;)

**Pull request merged**
